<a href="https://colab.research.google.com/github/diahangelika/data-analyst/blob/data-analyst/STATISTIKA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

STATISTIKA

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

uploaded = files.upload()

Saving Data-Penindakan-Pelanggaran-Lalu-Lintas.csv to Data-Penindakan-Pelanggaran-Lalu-Lintas.csv

In [ ]:
data_fr = pd.read_csv("/content/Data-Penindakan-Pelanggaran-Lalu-Lintas.csv")

data_fr

,bulan,wilayah,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,Januari,Bidang Dalops,44,139,0,0,73,0,0,0
1,Januari,Sudinhub Jakarta Pusat,47,2,52,0,184,237,15,97
2,Januari,Sudinhub Jakarta Utara,166,27,0,0,174,0,0,0
3,Januari,Sudinhub Jakarta Selatan,44,1,0,0,61,42,75,0
4,Januari,Sudinhub Jakarta Barat,184,70,0,0,202,10,5,0
5,Januari,Sudinhub Jakarta Timur,191,141,0,0,137,0,0,0
6,Februari,Bidang Dalops,37,143,0,0,95,2,1,0
7,Februari,Sudinhub Jakarta Pusat,48,7,42,0,175,396,21,143
8,Februari,Sudinhub Jakarta Utara,251,27,31,0,255,3,0,0
9,Februari,Sudinhub Jakarta Selatan,129,12,0,0,155,446,110,0
10,Februari,Sudinhub Jakarta Barat,229,60,0,0,245,12,4,0
11,Februari,Sudinhub Jakarta Timur,276,146,0,0,299,0,0,0
12,Maret,Bidang Dalops,90,203,0,0,150,18,2,0
13,Maret,Sudinhub Jakarta Pusat,68,10,0,0,146,216,1,58
14,Maret,Sudinhub Jakarta Utara,323,37,0,0,285,0,0,0
15,Maret,Sudinhub Jakarta Selatan,479,51,0,0,325,221,87,0
16,Maret,Sudinhub Jakarta Barat,270,101,0,0,318,20,11,0
17,Maret,Sudinhub Jakarta Timur,253,129,0,0,291,22,0,0
18,April,Bidang Dalops,78,108,0,0,139,0,2,0
19,April,Sudinhub Jakarta Pusat,93,21,0,0,166,99,5,117
20,April,Sudinhub Jakarta Utara,293,22,12,0,165,0,0,0
21,April,Sudinhub Jakarta Selatan,454,42,0,0,261,423,64,0
22,April,Sudinhub Jakarta Barat,233,97,0,0,252,0,1,0
23,April,Sudinhub Jakarta Timur,274,113,0,0,264,0,0,0
24,Mei,Bidang Dalops,47,88,0,0,57,0,0,0
25,Mei,Sudinhub Jakarta Pusat,30,10,0,0,46,447,72,244
26,Mei,Sudinhub Jakarta Utara,174,10,16,0,149,0,0,0
27,Mei,Sudinhub Jakarta Selatan,203,29,2,0,169,272,28,0
28,Mei,Sudinhub Jakarta Barat,156,82,0,0,107,0,0,0
29,Mei,Sudinhub Jakarta Timur,162,107,0,0,157,0,0,0
30,Juni,Bidang Dalops,113,129,0,0,119,7,2,0
31,Juni,Sudinhub Jakarta Pusat,24,9,0,0,90,806,8,414
32,Juni,Sudinhub Jakarta Utara,365,29,39,0,206,0,0,0
33,Juni,Sudinhub Jakarta Selatan,390,22,16,0,188,277,51,0
34,Juni,Sudinhub Jakarta Barat,176,81,0,0,157,62,6,0
35,Juni,Sudinhub Jakarta Timur,217,116,0,0,203,0,0,0
36,Juli,Bidang Dalops,72,80,0,0,38,0,0,0
37,Juli,Sudinhub Jakarta Pusat,12,6,0,0,11,146,3,0
38,Juli,Sudinhub Jakarta Utara,224,20,24,0,54,0,0,19
39,Juli,Sudinhub Jakarta Selatan,95,2,8,0,25,160,6,0
40,Juli,Sudinhub Jakarta Barat,36,32,0,0,29,0,0,0
41,Juli,Sudinhub Jakarta Timur,104,72,0,0,110,0,0,0

In [ ]:
#cara 1

data_bap = data_fr["bap_tilang"]

data_bap

0      44
1      47
2     166
3      44
4     184
5     191
6      37
7      48
8     251
9     129
10    229
11    276
12     90
13     68
14    323
15    479
16    270
17    253
18     78
19     93
20    293
21    454
22    233
23    274
24     47
25     30
26    174
27    203
28    156
29    162
30    113
31     24
32    365
33    390
34    176
35    217
36     72
37     12
38    224
39     95
40     36
41    104
Name: bap_tilang, dtype: int64

In [ ]:
mean_bap = data_bap.mean()
mean_bap

170.33333333333334

In [ ]:
median_bap = data_bap.median()
median_bap

164.0

In [ ]:
from statistics import mode

modus_bap = mode(data_bap)

modus_bap

44

In [ ]:
varian_bap = data_bap.var()

varian_bap

14520.910569105692

In [ ]:
standar_deviasi_bap = data_bap.std()

standar_deviasi_bap

120.50274091947324

In [ ]:
# kuartil

q1 = data_bap.quantile(0.25) #angka-angkanya 0.25 0.5 0.75 ini udah fix rumusnya buat nentuin q1,q2,q3
q2 = data_bap.quantile(0.5)
q3 = data_bap.quantile(0.75)

print(f" q1 = {q1}")
print(f" q2 = {q2}")
print(f" q3 = {q3}")

#IQR
iqr = q3-q1

# Mencari data outlier
lower_bound = q1 - 1.5 * iqr
# lower_bound = max(q1 - 1.5 * iqr, min(data))
upper_bound = q3 + 1.5 * iqr

outliers = []

for x in data_bap:
  if x < lower_bound or x > upper_bound:
    outliers.append(x)

data_bersih = []

for x in data_bap:
  if x not in outliers:
    data_bersih.append(x)

print("Q1:", q1)
print("Q2 (Median):", q2)
print("Q3:", q3)
print("IQR:", iqr)
print("batas bawah:", lower_bound)
print("batas atas:", upper_bound)
print("outliers:",outliers)
print("data bersih:",data_bersih)

 q1 = 69.0
 q2 = 164.0
 q3 = 246.5
Q1: 69.0
Q2 (Median): 164.0
Q3: 246.5
IQR: 177.5
batas bawah: -197.25
batas atas: 512.75
outliers: []
data bersih: [44, 47, 166, 44, 184, 191, 37, 48, 251, 129, 229, 276, 90, 68, 323, 479, 270, 253, 78, 93, 293, 454, 233, 274, 47, 30, 174, 203, 156, 162, 113, 24, 365, 390, 176, 217, 72, 12, 224, 95, 36, 104]

ASSIGNMENT

In [ ]:
data_fr = pd.read_csv("/content/Data-Penindakan-Pelanggaran-Lalu-Lintas.csv")

data_fr

,bulan,wilayah,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,Januari,Bidang Dalops,44,139,0,0,73,0,0,0
1,Januari,Sudinhub Jakarta Pusat,47,2,52,0,184,237,15,97
2,Januari,Sudinhub Jakarta Utara,166,27,0,0,174,0,0,0
3,Januari,Sudinhub Jakarta Selatan,44,1,0,0,61,42,75,0
4,Januari,Sudinhub Jakarta Barat,184,70,0,0,202,10,5,0
5,Januari,Sudinhub Jakarta Timur,191,141,0,0,137,0,0,0
6,Februari,Bidang Dalops,37,143,0,0,95,2,1,0
7,Februari,Sudinhub Jakarta Pusat,48,7,42,0,175,396,21,143
8,Februari,Sudinhub Jakarta Utara,251,27,31,0,255,3,0,0
9,Februari,Sudinhub Jakarta Selatan,129,12,0,0,155,446,110,0
10,Februari,Sudinhub Jakarta Barat,229,60,0,0,245,12,4,0
11,Februari,Sudinhub Jakarta Timur,276,146,0,0,299,0,0,0
12,Maret,Bidang Dalops,90,203,0,0,150,18,2,0
13,Maret,Sudinhub Jakarta Pusat,68,10,0,0,146,216,1,58
14,Maret,Sudinhub Jakarta Utara,323,37,0,0,285,0,0,0
15,Maret,Sudinhub Jakarta Selatan,479,51,0,0,325,221,87,0
16,Maret,Sudinhub Jakarta Barat,270,101,0,0,318,20,11,0
17,Maret,Sudinhub Jakarta Timur,253,129,0,0,291,22,0,0
18,April,Bidang Dalops,78,108,0,0,139,0,2,0
19,April,Sudinhub Jakarta Pusat,93,21,0,0,166,99,5,117
20,April,Sudinhub Jakarta Utara,293,22,12,0,165,0,0,0
21,April,Sudinhub Jakarta Selatan,454,42,0,0,261,423,64,0
22,April,Sudinhub Jakarta Barat,233,97,0,0,252,0,1,0
23,April,Sudinhub Jakarta Timur,274,113,0,0,264,0,0,0
24,Mei,Bidang Dalops,47,88,0,0,57,0,0,0
25,Mei,Sudinhub Jakarta Pusat,30,10,0,0,46,447,72,244
26,Mei,Sudinhub Jakarta Utara,174,10,16,0,149,0,0,0
27,Mei,Sudinhub Jakarta Selatan,203,29,2,0,169,272,28,0
28,Mei,Sudinhub Jakarta Barat,156,82,0,0,107,0,0,0
29,Mei,Sudinhub Jakarta Timur,162,107,0,0,157,0,0,0
30,Juni,Bidang Dalops,113,129,0,0,119,7,2,0
31,Juni,Sudinhub Jakarta Pusat,24,9,0,0,90,806,8,414
32,Juni,Sudinhub Jakarta Utara,365,29,39,0,206,0,0,0
33,Juni,Sudinhub Jakarta Selatan,390,22,16,0,188,277,51,0
34,Juni,Sudinhub Jakarta Barat,176,81,0,0,157,62,6,0
35,Juni,Sudinhub Jakarta Timur,217,116,0,0,203,0,0,0
36,Juli,Bidang Dalops,72,80,0,0,38,0,0,0
37,Juli,Sudinhub Jakarta Pusat,12,6,0,0,11,146,3,0
38,Juli,Sudinhub Jakarta Utara,224,20,24,0,54,0,0,19
39,Juli,Sudinhub Jakarta Selatan,95,2,8,0,25,160,6,0
40,Juli,Sudinhub Jakarta Barat,36,32,0,0,29,0,0,0
41,Juli,Sudinhub Jakarta Timur,104,72,0,0,110,0,0,0

In [ ]:
#NOMOR 3

data_stop = data_fr["stop_operasi"]

mean_stop = data_stop.mean()
median_stop = data_stop.median()

print("mean", mean_stop)
print("median", median_stop)

mean 62.69047619047619
median 46.5

In [ ]:
standar_deviasi_stop = data_stop.std()
q1 = data_stop.quantile(0.25)
q2 = data_stop.quantile(0.5)
q3 = data_stop.quantile(0.75)

print("standar deviasi", standar_deviasi_stop)
print(f" q1 = {q1}")
print(f" q2 = {q2}")
print(f" q3 = {q3}")

standar deviasi 52.447645484243445
 q1 = 20.25
 q2 = 46.5
 q3 = 105.5

In [ ]:
data_fr.iloc[0:, 2:]

,bap_tilang,stop_operasi,bap_polisi,stop_operasi_polisi,penderekan,ocp_roda_dua,ocp_roda_empat,angkut_motor
0,44,139,0,0,73,0,0,0
1,47,2,52,0,184,237,15,97
2,166,27,0,0,174,0,0,0
3,44,1,0,0,61,42,75,0
4,184,70,0,0,202,10,5,0
5,191,141,0,0,137,0,0,0
6,37,143,0,0,95,2,1,0
7,48,7,42,0,175,396,21,143
8,251,27,31,0,255,3,0,0
9,129,12,0,0,155,446,110,0
10,229,60,0,0,245,12,4,0
11,276,146,0,0,299,0,0,0
12,90,203,0,0,150,18,2,0
13,68,10,0,0,146,216,1,58
14,323,37,0,0,285,0,0,0
15,479,51,0,0,325,221,87,0
16,270,101,0,0,318,20,11,0
17,253,129,0,0,291,22,0,0
18,78,108,0,0,139,0,2,0
19,93,21,0,0,166,99,5,117
20,293,22,12,0,165,0,0,0
21,454,42,0,0,261,423,64,0
22,233,97,0,0,252,0,1,0
23,274,113,0,0,264,0,0,0
24,47,88,0,0,57,0,0,0
25,30,10,0,0,46,447,72,244
26,174,10,16,0,149,0,0,0
27,203,29,2,0,169,272,28,0
28,156,82,0,0,107,0,0,0
29,162,107,0,0,157,0,0,0
30,113,129,0,0,119,7,2,0
31,24,9,0,0,90,806,8,414
32,365,29,39,0,206,0,0,0
33,390,22,16,0,188,277,51,0
34,176,81,0,0,157,62,6,0
35,217,116,0,0,203,0,0,0
36,72,80,0,0,38,0,0,0
37,12,6,0,0,11,146,3,0
38,224,20,24,0,54,0,0,19
39,95,2,8,0,25,160,6,0
40,36,32,0,0,29,0,0,0
41,104,72,0,0,110,0,0,0

In [ ]:
data_fr.iloc[0:, 0:2]

       bulan                   wilayah
0    Januari             Bidang Dalops
1    Januari    Sudinhub Jakarta Pusat
2    Januari    Sudinhub Jakarta Utara
3    Januari  Sudinhub Jakarta Selatan
4    Januari    Sudinhub Jakarta Barat
5    Januari    Sudinhub Jakarta Timur
6   Februari             Bidang Dalops
7   Februari    Sudinhub Jakarta Pusat
8   Februari    Sudinhub Jakarta Utara
9   Februari  Sudinhub Jakarta Selatan
10  Februari    Sudinhub Jakarta Barat
11  Februari    Sudinhub Jakarta Timur
12     Maret             Bidang Dalops
13     Maret    Sudinhub Jakarta Pusat
14     Maret    Sudinhub Jakarta Utara
15     Maret  Sudinhub Jakarta Selatan
16     Maret    Sudinhub Jakarta Barat
17     Maret    Sudinhub Jakarta Timur
18     April             Bidang Dalops
19     April    Sudinhub Jakarta Pusat
20     April    Sudinhub Jakarta Utara
21     April  Sudinhub Jakarta Selatan
22     April    Sudinhub Jakarta Barat
23     April    Sudinhub Jakarta Timur
24       Mei             Bidang Dalops
25       Mei    Sudinhub Jakarta Pusat
26       Mei    Sudinhub Jakarta Utara
27       Mei  Sudinhub Jakarta Selatan
28       Mei    Sudinhub Jakarta Barat
29       Mei    Sudinhub Jakarta Timur
30      Juni             Bidang Dalops
31      Juni    Sudinhub Jakarta Pusat
32      Juni    Sudinhub Jakarta Utara
33      Juni  Sudinhub Jakarta Selatan
34      Juni    Sudinhub Jakarta Barat
35      Juni    Sudinhub Jakarta Timur
36      Juli             Bidang Dalops
37      Juli    Sudinhub Jakarta Pusat
38      Juli    Sudinhub Jakarta Utara
39      Juli  Sudinhub Jakarta Selatan
40      Juli    Sudinhub Jakarta Barat
41      Juli    Sudinhub Jakarta Timur

In [ ]:
mean_data = data_fr.iloc[0:, 2:].mean()
median_data = data_fr.iloc[0:, 2:].median()

print(" MEAN : ")
print(mean_data)
print(" MEDIAN : ")
print(median_data)

 MEAN :
bap_tilang             170.333333
stop_operasi            62.690476
bap_polisi               5.761905
stop_operasi_polisi      0.000000
penderekan             160.285714
ocp_roda_dua           103.428571
ocp_roda_empat          13.809524
angkut_motor            26.000000
dtype: float64
 MEDIAN :
bap_tilang             164.0
stop_operasi            46.5
bap_polisi               0.0
stop_operasi_polisi      0.0
penderekan             157.0
ocp_roda_dua             5.0
ocp_roda_empat           1.0
angkut_motor             0.0
dtype: float64

In [ ]:
standar_deviasi_data = data_fr.iloc[0:, 2:].std()
q1 = data_fr.iloc[0:, 2:].quantile(0.25)
q2 = data_fr.iloc[0:, 2:].quantile(0.5)
q3 = data_fr.iloc[0:, 2:].quantile(0.75)

print(" standar deviasi = \n", standar_deviasi_data)
print(f" q1 = \n{q1}")
print(f" q2 = \n{q2}")
print(f" q3 = \n{q3}")

 standar deviasi =
 bap_tilang             120.502741
stop_operasi            52.447645
bap_polisi              12.930979
stop_operasi_polisi      0.000000
penderekan              85.526001
ocp_roda_dua           178.136032
ocp_roda_empat          27.480581
angkut_motor            78.057515
dtype: float64
 q1 =
bap_tilang             69.00
stop_operasi           20.25
bap_polisi              0.00
stop_operasi_polisi     0.00
penderekan             98.00
ocp_roda_dua            0.00
ocp_roda_empat          0.00
angkut_motor            0.00
Name: 0.25, dtype: float64
 q2 =
bap_tilang             164.0
stop_operasi            46.5
bap_polisi               0.0
stop_operasi_polisi      0.0
penderekan             157.0
ocp_roda_dua             5.0
ocp_roda_empat           1.0
angkut_motor             0.0
Name: 0.5, dtype: float64
 q3 =
bap_tilang             246.50
stop_operasi           105.50
bap_polisi               0.00
stop_operasi_polisi      0.00
penderekan             205.25
ocp_roda_dua           156.50
ocp_roda_empat           7.50
angkut_motor             0.00
Name: 0.75, dtype: float64

In [ ]:
bulan = data_fr["bulan"]
a = "" # kalo pake list ([]) harus diakses pake index
rata_rata = {} # set dictionary tidak bisa data ganda makannya yang tampil mau dia satu aja datanya
for i in bulan:
  if i !=a:
    a = i
    hasil = data_fr.loc[data_fr["bulan"] == i, "stop_operasi"].mean()
    rata_rata.update({i : hasil}) # set dia pake update nambahin datanya

print(rata_rata)

{'Januari': 63.333333333333336, 'Februari': 65.83333333333333, 'Maret': 88.5, 'April': 67.16666666666667, 'Mei': 54.333333333333336, 'Juni': 64.33333333333333, 'Juli': 35.333333333333336}

In [ ]:
januari = data_fr.loc[data_fr["bulan"] == "Januari", "stop_operasi"].mean()
feb = data_fr.loc[data_fr["bulan"] == "Februari", "stop_operasi"].mean()
mar = data_fr.loc[data_fr["bulan"] == "Maret", "stop_operasi"].mean()
apr = data_fr.loc[data_fr["bulan"] == "April", "stop_operasi"].mean()
mei = data_fr.loc[data_fr["bulan"] == "Mei", "stop_operasi"].mean()
juni = data_fr.loc[data_fr["bulan"] == "Juni", "stop_operasi"].mean()
juli = data_fr.loc[data_fr["bulan"] == "Juli", "stop_operasi"].mean()

print(f"rata rata januari = {januari}")
print(f"rata rata Februari = {feb}")
print(f"rata rata Maret = {mar}")
print(f"rata rata April = {apr}")
print(f"rata rata Mei = {mei}")
print(f"rata rata Juni = {juni}")
print(f"rata rata Juli = {juli}")

rata rata januari = 63.333333333333336
rata rata Februari = 65.83333333333333
rata rata Maret = 88.5
rata rata April = 67.16666666666667
rata rata Mei = 54.333333333333336
rata rata Juni = 64.33333333333333
rata rata Juli = 35.333333333333336